#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# 后台
# 登录
admin_login:
    path: /admin
    controller: App\Controller\SecurityController::login
# 退出
admin_logout:
    path: /admin/logout
    controller: App\Controller\Admin\LoginController::logout
# 导航
admin_nav:
    path: /admin/nav
    controller: App\Controller\Admin\AppController::nav
